[general]
doc = """This is a very simple proxy between Websockets and Unix domain sockets. It acts
as a Websocket server while forwarding all messages to a specified Unix socket.

The messages forwarded to Unix socket are length-delimited, where length of
each message is encoded as 32-bit native-endian binary number. The length is
prepended to each message forwarded to Unix socket.

Conversely, each message coming from Unix socket is decoded as 32-bit
native-endian length followed by the payload. It is attempted to interpret the
message as utf-8 string and send it over websocket as text message. However, if
the conversion fails, the message is sent as binary."""

[[param]]
name = "socket_path"
type = "::std::path::PathBuf"
optional = false
doc = "Unix socket path"

[[param]]
name = "bind_addr"
type = "::std::net::SocketAddr"
optional = false
doc = "TCP/IP socket address of the Websocket server"
